export * from './About';
export * from './Contact';
export * from './Common';
export * from './Faq';
export * from './Gallery';
export * from './Home';
export * from './NoMatch';
export * from './Project';
export * from './Services';
