export const ApiPath = {
  PATH: {
    DATA_MANAGEMENT: '/v1/pipeline',
    DATA_MANAGEMENT_BY_DMAIN: '/v1/pipeline/all',
    DATA_MANAGEMENT_SYNC: '/v1/pipeline',
    DATA_MANAGEMENT_DEFAULT_ACOUNT_BY_PIPELINE_KEY: '/v1/count/pipeline/{pipelineKey}',
    DATA_MANAGEMENT_DEFAULT_ACOUNT: '/v1/count/pipeline',
    DATA_MANAGEMENT_PIPELINE_CONVERT: '/v1/convert/pipeline',
    DATA_MANAGEMENT_PIPELINE_EXISTS: '/v1/exists/pipeline',
    DATA_MANAGEMENT_PIPELINE_ADD: '/v1/add/pipeline',
    DATA_MANAGEMENT_ALL_PIPELINE: '/v1/all/pipeline',
    LIVE_USER: '/v1/live-user',
    LIVE_USER_ACTIVE_PAGE: '/v1/live-user/active-page',
    LIVE_USER_CLEAR_ACTIVE_PAGE: '/v1/live-user/clear-active-page',
    DM_SYNC_CURRENT_STATUS: '/v1/pipeline/{entity}/{isAcl}/rsync/current/{apiKey}',
    DM_SYNC_HISTORY: '/v1/pipeline/{entity}/{isAcl}/rsync/{apiKey}',
    DATA_ANALYZER: {
      ALL: '/v1/dm/da/alldataanalyzerjobconfig',
      GET_DELETE: '/v1/dm/da/dataanalyzerjobconfig/{key}',
      CREATE_UPDATE: '/v1/dm/da/dataanalyzerjobconfig',
      RESULT_ALL: '/v1/dm/da/alldataanalysisresult',
      RESULT_BY_KEY: '/v1/dm/da/dataanalysisresult/{dataAnalyzerId}',
    },
    USER_INTERACTION: {
      ALL: '/v1/live-user/chats',
      ALL_BY_USER_BY_CURRENT: '/v1/live-user/chats/{fromUser}',
      ALL_BY_USER: '/v1/live-user/chats/{fromUser}/{toUser}',
      CREATE: '/v1/live-user/chat',
      UPDATE: '/v1/live-user/chat/send',
      CLOSE_CHAT: '/v1/live-user/chat/close',
      OPEN_CHAT: '/v1/live-user/chat/open',
      GET_AND_DELETE_BY_KEY: '/v1/live-user/chat/{key}',
    },
    WORKSPACE: '/v1/workspacemenu',
  },
  METHOD: {
    GET: 'get',
    POST: 'post',
    PUT: 'put',
    DELETE: 'delete',
  },
};
