import { IEndpoint } from 'store/states';

export const DataApiPath: { [x: string]: string | IEndpoint } = {
  chassisEquipmentMaintenance: 'chassisType',
  containerHandlingVehicleMaintenance: 'containerhandlingvehicle',
  lineMaintenance: 'line',
  tractorEquipmentMaintenance: 'internalTractor',
  quayCraneMaintenance: 'qc',
  terminalConfig: 'terminals?portId=1',
  stationConfig: 'stations?portId=1',
  wagonTypeGroupsConfig: 'wagon-type-groups',
  wagonTypesConfig: 'wagon-types',
  itPager: 'pager',
  yardCraneMaintenance: 'yardcrane',
  yardBlockMaintenance: 'yardblocksonly',
  yardZoneMaintenance: 'yardzone',
  locationGroupMaintenance: 'locationgroup',

  berthMaintenance: 'berth',
  workingShift: 'workingshift',
  lineServiceOverview: 'lineService',
  lineServiceMaritimeInformation: 'lineService',
  provinceMaintenance: 'province',
  countryMaintenance: 'country',
  portMaintenance: 'port',
  vesselMaintenance: 'vessel',
  pilotOnBoardMaintenance: 'pilotonboard',
  portOfCallMaintenance: 'lineService',
  containerSizeMaintenance: 'containersizespec',
  containerTypeMaintenance: 'containertypespec',
  specialHandlingCodeMaintenance: 'specialhandlingcode',
  containerTypeGroupMaintenance: 'containertypegroup',
  dangerousCodeMaintenance: 'dangerouscode',
  holdCodeMaintenance: 'holdcode',
  equipmentCodeMaintenance: 'equipmenthandling',
  codeLibrary: 'policycode',
  voyageGeneralInformation: 'voyage',
  damageCodeMaintenance: 'damagecode',
  reasonCodeMaintenance: 'reasoncode',
  tieDownLocationMaintenance: 'tie-down-locations',
  qcMoveLogMaintenance: 'qc-move-logs',
  ycWorkloadMaintenance: 'ycWorkloadSetting',
  ycWorkloadMonitoring: 'ycWorkloadSetting',
  gradeCodeMaintenance: 'gradeCode',
  gateQueue: 'tractorQMon',
  serviceArea: 'serviceArea',
  msshDeployment: 'msshPool',
  qcDeployment: 'qcPool',
  operatorConfig: 'operators?portId=1',
  // tractorPairing: './src/entrypoint/TractorPairing/TractorPairing.tsx',tie-down-locations
};
